run-dist:
	./build/install/app/bin/app
run-help:
	./build/install/app/bin/app -h
run-version:
	./build/install/app/bin/app -V
run-default:
	./build/install/app/bin/app /home/john/gitDir/java-project-71/app/src/test/resources/file1.java /home/john/gitDir/java-project-71/app/src/test/resources/file2.java
report:
	./gradlew jacocoTestReport
