name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./app


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      
    - name: Init gradle wrapper
      run: gradle wrapper

    - name: build
      run: ./gradlew build

    - name: test
      run: ./gradlew test
  
    - name: Test Coverage  
      uses: paambaati/codeclimate-action@v2.7.1
      env:
        CC_TEST_REPORTER_ID: ff44d9af835bac9ce21bc6297c30ab3a7e0e70533c653bd501ec66e1201af182
      with:
        coverageLocations: ${{github.workspace}}app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
        coverageCommand: ./gradlew jacocoTestReport


